#application: atrack
application: bittrk  
version: 1
runtime: python
api_version: 1

handlers:

- url: /ntrack
  script: main.py

- url: /static/
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/(.*)

- url: /app-admin/
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /debug
  script: debug.py

#- url: /.*
#  script: 404.py


