application: atrack-torrent-tracker
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
    Content-Type: 'text/html; charset=utf-8'
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
  redirect_http_response_code: 301
  
- url: /
  static_dir: static
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: 'max-age=86400; includeSubDomains'
