module: instance-1
runtime: python27
api_version: 1
threadsafe: false
  
handlers:
- url: /announce
  script: main.py
  secure: always
  
# This deals with all kind of broken links and people that don't know how to
# configure their BT clients. Saves some BW and CPU avoiding the trigger of 404 errors.
- url: /announce[^?].*
  static_files: null.html
  upload: null.html
  
# Scrape is not implemented yet.
- url: /scrape
  static_files: null.html
  upload: null.html
  
- url: /ntrack
  script: main.py
  secure: always
  
- url: /mestat
  script: mestat.py
  secure: always
  
# When the URL of the tracker is entered on the browser, redirect to website.
- url: /
  script: redir.py
  secure: always
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
  
- url: /.*
  static_files: null.html
  upload: null.html