application: atrack-tracker-asia-e2
version: 1
runtime: python27
api_version: 1
threadsafe: false
  
handlers:
- url: /
  static_files: redirect.html
  upload: redirect.html
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
  
- url: /announce
  script: main.py
  secure: always
  
- url: /announce[^?].*
  static_files: redirect.html
  upload: redirect.html
  
- url: /ntrack
  script: main.py
  secure: always
  
- url: /scrape
  static_files: null.html
  upload: null.html
  
- url: /mestat
  script: mestat.py
  secure: always
  
- url: /.*
  static_files: redirect.html
  upload: redirect.html