application: atrack-torrent-tracker
version: 1
module: instance-2
runtime: python27
api_version: 1
threadsafe: false
instance_class: B1
basic_scaling:
  idle_timeout: 2m
  max_instances: 1
  
handlers:
- url: /
  static_files: redirect.html
  upload: redirect.html
  secure: optional
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
  
- url: /announce
  script: main.py
  secure: optional
  
- url: /ntrack
  script: main.py
  secure: optional
  
- url: /mestat
  script: mestat.py
  secure: always