service: redirect
runtime: php73
automatic_scaling:
  max_instances: 1
  
# To make redirect work while the instance is over quota.
error_handlers:
- error_code: over_quota
  file: over_quota.html
  
handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
  
- url: /.*
  script: auto