service: redirect
runtime: php55
api_version: 1
threadsafe: true
instance_class: B1
basic_scaling:
  idle_timeout: 1m
  max_instances: 1
  
# To make redirect work while the instance is over quota.
error_handlers:
- error_code: over_quota
  file: over_quota.html
  
handlers:
# To let GAE run this backend instance.
- url: /_ah/start
  script: $PYTHON_LIB/default_start_handler.py
  login: admin
  secure: never
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
  
- url: /.*
  script: index.php